### PR TITLE
Add CNAME file to github pages branch

### PR DESCRIPTION
**Pull request by kumuditha-udayanga**
* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- [x] Bug fix
- [ ] Feature implementation
- [ ] Doc updates

* **Related Issue**

#90 

* **What changes have you introduced?**

* **Does this PR introduce a breaking change?**
no

* **Preview / Steps to verify your work**:

### CODE REVIEW

**Comment by kumuditha-udayanga** [comment]
@mariobehling Please review this :)

**Comment by mariobehling** [comment]
Ok, it is deployed now, but I think there is a conflict somewhere, maybe readme.html, index.html? Please check https://docs.pslab.io/

**Comment by mariobehling** [comment]
Let's wait a bit. Might be working soon.

**Comment by kumuditha-udayanga** [comment]
@mariobehling Okay I'll stay in touch 🙂

**Comment by kumuditha-udayanga** [comment]
@mariobehling It's working now 🥳🎉

**Pull request merged**
