### PR TITLE
Fixed Logo Issue

### PR DESCRIPTION
**Pull request by nikhanal**
* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our [guidelines](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia/)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- [x] Bug fix
- [ ] Feature implementation
- [ ] Doc updates

* **Related Issue**

* **What changes have you introduced?**

I have added logo fo page in _static folder and I added path for the logo in conf.py file

* **Does this PR introduce a breaking change?**

* **Preview / Steps to verify your work**:

### CODE REVIEW

**Comment by bessman** [comment]
This looks OK to me!

@orangecms Should the logo be in images/ or is _static/ OK?

**Review by bessman — APPROVED** [review]

**Comment by nikhanal** [comment]
I think images would be suitable path.
Let me pull request

**Review by orangecms — APPROVED** [review]
Awesome, thank you! :-)

**Comment by nikhanal** [comment]
Should I change the path for logo?

**Comment by orangecms** [comment]
From a separations of concernc perspective, `_static/` is okay here. I think `images/` is more for the actual content, but this is a layout thing.

**Comment by nikhanal** [comment]
Ok

**Pull request merged**
