### PR TITLE
Added New documentation #61

### PR DESCRIPTION
**Pull request by abhrakantidubey**
* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- [ ] Bug fix
- [x] Feature implementation
- [x] Doc updates

* **Related Issue**

* **What changes have you introduced?**

* **Does this PR introduce a breaking change?**

* **Preview / Steps to verify your work**:

### CODE REVIEW

**Comment by NishithP2004** [comment]
Please delete the newly created ``Compass.md`` file

**Comment by abhrakantidubey** [comment]
sorry bhaiya galti se ho gya but mai kaise karu?

**Comment by abhrakantidubey** [comment]
Mai confuse ho gya hun. I am sure I will lose in gci

**Comment by NishithP2004** [comment]
Please delete this file as well
https://github.com/abhrakantidubey/pslab-documentation/blob/master/Added%20compass%20documentation.md

**Comment by abhrakantidubey** [comment]
bhaiya deleted then?

**Comment by abhrakantidubey** [comment]
hi bhaiya are u there?

**Comment by NishithP2004** [comment]
LGTM
@cweitat @mariobehling Please have a look

**Comment by abhrakantidubey** [comment]
sorry, sir I couldn't understand. What to do after this? or shall I make a new md.file?on this experiment

**Comment by abhrakantidubey** [comment]
Or is it done?

**Comment by NishithP2004** [comment]
Just sit back and relax...a mentor will look into it and merge it.

**Comment by cweitat** [comment]
before creating any PR, please create an issue to have a more detailed explanation of what you want to do

**Comment by abhrakantidubey** [comment]
ok sir

**Comment by cweitat** [comment]
There's also quite an number of grammer and spelling mistakes in the first paragraph and I haven't even looked at others. Look through and make necessary changes to it. Also, provide a link to the your hosted page so we can see the difference.

**Comment by abhrakantidubey** [comment]
Sir, sorry to ask but what is the hosted page?

**Comment by NishithP2004** [comment]
> Please do the requested changes.
> Learn more About hosted page: https://pages.github.com/
> 
> PS. It’s known as GitHub Pages

You are supposed to create a preview link to view the changes.

**Comment by abhrakantidubey** [comment]
Is it correct?

**Comment by abhrakantidubey** [comment]
This is the old one.
# pslab-Compass
PSLab Documentation and Experiments https://docs.pslab.io
# EXPERIMENT TO CHECK THAT Ps-lab COMPASS DEFLECTS WHEN IT COMES IN CONTACT WITH MAGNET.
+ 1.REQUIREMENTS:
Android phone with a) compass sensor and b) PSLab app installed,magnet and a compass.
 1.STEPS:
 STEP 1:
Take the magnet near to the compass.You will see that compass has deflecting.
STEP 2:
Take the magnet near to the Ps-lab Compass.You will see that, there is no delection in it.
+ 3.RESULT:
Thus through this experiment it shows that Magnets do interact with the magnet inside a normal but that show no effect on the PSLab compass.
+ 4.CONCLUSION:
By this Experiment we can understand that the PSLab compass uses GPS and other sensors to provide us directions and Do not uses any magnet to find directions. It further examine the GPS and Sensor readings and then using this data calibrate the compass needles according to our phones calibration and general position.
YOU CAN CHECK THE SCREENSHOTS.
Ps-lab compass near the magnet
WhatsApp Image 2020-01-03 at 10 30 57 AM
Ps-lab compass normal
WhatsApp Image 2020-01-03 at 10 30 57 AM (1)

**Comment by cweitat** [comment]
PSLab. Your commas and full stops have no space after. PSLab Compass without dashes.

create a issue and edit your PR description by typing # and the issue number

**Comment by abhrakantidubey** [comment]
ya sure sir.

**Comment by abhrakantidubey** [comment]
here is the link https://github.com/fossasia/pslab-documentation/issues/61

**Comment by mariobehling** [comment]
Closing this due to inactivity.

**Pull request closed without merging**
