### PR TITLE
Added compass Documentation.md

### PR DESCRIPTION
**Pull request by abhrakantidubey**
* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- [ ] Bug fix
- [x] Feature implementation
- [x] Doc updates

* **Related Issue**

* **What changes have you introduced?**

* **Does this PR introduce a breaking change?**

* **Preview / Steps to verify your work**:

### CODE REVIEW

**Comment by abhrakantidubey** [comment]
Sir, In google codein task they have said"PSLab Compass: How to find directions with your Phone and the PSLab app? Propose an Experiment - FOSSASIA"
Shall I make experiment with compass again?
Sir,in my md. file the screenshots are original and it's mine only?

**Comment by abhrakantidubey** [comment]
# pslab-Compass
PSLab Documentation and Experiments https://docs.pslab.io
# EXPERIMENT TO CHECK THAT Ps-lab COMPASS DEFLECTS WHEN IT COMES IN CONTACT WITH MAGNET.
+ 1.REQUIREMENTS:
Android phone with a) compass sensor and b) PSLab app installed,magnet and a compass.
 1.STEPS:
 STEP 1:
Take the magnet near to the compass.You will see that compass has deflecting.
STEP 2:
Take the magnet near to the Ps-lab Compass.You will see that, there is no delection in it.
+ 3.RESULT:
Thus through this experiment it shows that Magnets do interact with the magnet inside a normal but that show no effect on the PSLab compass.
+ 4.CONCLUSION:
By this Experiment we can understand that the PSLab compass uses GPS and other sensors to provide us directions and Do not uses any magnet to find directions. It further examine the GPS and Sensor readings and then using this data calibrate the compass needles according to our phones calibration and general position.
YOU CAN CHECK THE SCREENSHOTS.
Ps-lab compass near the magnet
WhatsApp Image 2020-01-03 at 10 30 57 AM
Ps-lab compass normal
WhatsApp Image 2020-01-03 at 10 30 57 AM (1)

**Comment by abhrakantidubey** [comment]
As per your request, I have made a new project on the Ps-lab compass. Hope You would like it.Thank You

**Comment by NishithP2004** [comment]
Please add this data to the compass.md file

**Comment by abhrakantidubey** [comment]
Hi bhaiya . How will I do this?Actually i am a beginner

**Comment by abhrakantidubey** [comment]
https://github.com/abhrakantidubey/pslab-documentation/blob/master/tutorials/compass.md

**Comment by NishithP2004** [comment]
> https://github.com/abhrakantidubey/pslab-documentation/blob/master/tutorials/compass.md

This is what is required ...please create a PR from this branch.

**Comment by abhrakantidubey** [comment]
ok bhaiya let me try

**Comment by abhrakantidubey** [comment]
bhaiya pls check it if I am not wrong https://github.com/fossasia/pslab-documentation/pull/59

**Comment by NishithP2004** [comment]
Please close this pr

**Pull request merged**
