### PR TITLE
Update compass.md

### PR DESCRIPTION
**Pull request by coder135792468**
Added Experiment number 3 
#60 
https://github.com/coder135792468/pslab-documentation/blob/master/tutorials/compass.md

### CODE REVIEW

**Comment by coder135792468** [comment]
@mariobehling @hpdang any one plz merge it

**Comment by coder135792468** [comment]
@NishithP2004 I think I have to write my experiment .
In the task it is written that I just have to write my experiment .

**Comment by NishithP2004** [comment]
Your experiment contradicts experiment 2.

**Comment by NishithP2004** [comment]
> @NishithP2004 I think I have to write my experiment .
> In the task it is written that I just have to write my experiment .

Yes, but that should not be the same thing which is already present.It should be something new.

**Comment by coder135792468** [comment]
@NishithP2004 should I do an experiment using Magent or it also present ?

**Comment by NishithP2004** [comment]
Already 2 magnet related experiments are present if I'm not mistaken.

**Comment by coder135792468** [comment]
@NishithP2004 the what experiment I can add ?
Should I add both magnet or wire experiment ?

**Comment by NishithP2004** [comment]
Think of something ...🤔

**Comment by cweitat** [comment]
think of something that is not already in here

**Comment by mariobehling** [comment]
There were several compass.md files in different folders. Let's keep to one md file and improve it. Please check if content is duplicate.

**Comment by coder135792468** [comment]
@mariobehling okk sir I am thinking about new experiment

**Pull request closed without merging**
