### PR TITLE
Update sphinx with recommonmark

### PR DESCRIPTION
**Pull request by vidhyav656**
https://github.com/fossasia/pslab-documentation/pull/50#issuecomment-548317314

* **Please check if the PR fulfills these requirements**
- [ x ] The commit message follows our guidelines
- [ x ] Tests for the changes have been added (for bug fixes / features)
- [ x ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- [ x ] Bug fix
- [ ] Feature implementation
- [ ] Doc updates

* **Related Issue**

#50 

* **What changes have you introduced?**
Added recommonmark  extension to build markdown files.

* **Does this PR introduce a breaking change?**
Its adds the extension of recommonmark to support markdown files.

* **Preview / Steps to verify your work**:
https://gitlab.com/vidhyav656/fossasia-pslab-documentation/tree/master

### CODE REVIEW

**Comment by mariobehling** [comment]
Ok, let's try. Thanks.

**Comment by mariobehling** [comment]
Build is still failing. Please see here: https://github.com/fossasia/pslab-documentation/issues/51

**Comment by mariobehling** [comment]
Please also check if we can have the Table in MD in the documentation: 
https://github.com/fossasia/pslab-documentation/blob/master/index.rst

**Comment by vidhyav656** [comment]
Okay. Its issues related to markdown table?

**Comment by mariobehling** [comment]
You could check details yourself by setting it up on your system: https://readthedocs.org. It is pretty quickly done.

**Comment by vidhyav656** [comment]
@Dishebh can you help me with this?

**Comment by Dishebh** [comment]
@vidhyav656 I am sorry but I am stuck in some other issue lately. I will let you know as soon as I am done with it.

**Pull request merged**
