### PR TITLE
Add screenshots for Gas Sensor and Dust Sensor

### PR DESCRIPTION
**Pull request by hoangdatngo**
I add layout screenshots of two instruments:

- Gas Sensor

- Dust Sensor
## Preview:
dust1
gas1

This is my work for task: https://codein.withgoogle.com/dashboard/task-instances/4779653999362048/

### CODE REVIEW

**Comment by hoangdatngo** [comment]
@hpdang, @mariobehling Can any mentor please review my MR?

**Comment by cweitat** [comment]
I only see hyperlinks and no image

**Comment by cweitat** [comment]
you need to show the images and not just the link

**Comment by hoangdatngo** [comment]
@cweitat I have update it, can you please review it again?

**Comment by cweitat** [comment]
too large, scale down the image instead of covering entire page

**Comment by hoangdatngo** [comment]
@cweitat I have scale down the image. Can you please review it again?

**Comment by cweitat** [comment]
I can't see the changes. Do you have screenshots or a hosted Github pages?

**Comment by cweitat** [comment]
You added screenshots but no explanation then this page is for ?

**Pull request merged**
