### PR TITLE
Add screenshots for two instruments

### PR DESCRIPTION
**Pull request by makoteq**
I added Layout screenshots for two instruments

- Barometr

- thermometr

### CODE REVIEW

**Comment by makoteq** [comment]
@NishithP2004 Can you merge?

**Comment by NishithP2004** [comment]
Sorry I don't have write acces.Plus another approval from a mentor is
required.

**Comment by makoteq** [comment]
@cweitat  Can you review?

**Comment by makoteq** [comment]
@cweitat I changed the file names

**Comment by makoteq** [comment]
@fcartegnie I have squashed commits

**Comment by makoteq** [comment]
@fcartegnie I deleted unrelated commits

**Comment by fcartegnie** [comment]
I stop reviewing these. Obviously not everyone aim for code quality.

**Pull request closed without merging**
