### PR TITLE
Added New Compass Experiment

### PR DESCRIPTION
**Pull request by Sid911**
* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [x] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- [ ] Bug fix
- [ ] Feature implementation
- [x] Doc updates

* **What changes have you introduced?**
Added new experiment on how to navigate using pslab compass. This is a technique which has been used to navigate and is still applicable to this date using just a compass and a physical map.

* **Does this PR introduce a breaking change?**
No, not really

* **Preview / Steps to verify your work**:
image

- Go to https://github.com/Sid911/pslab-documentation/blob/master/tutorials/compass.md
- Navigate to the 3rd experiment 😇

### CODE REVIEW

**Comment by Sid911** [comment]
@cweitat @fcartegnie please review... this took a bit of time to research and make good looking photos 😇

**Comment by Sid911** [comment]
I used Grammarly to make sure there are no mistakes in spelling while I typed that 😇
image

**Comment by kumuditha-udayanga** [comment]
Looks Good to me!

**Comment by fcartegnie** [comment]
pics are way too big.
pngcrush.

**Comment by fcartegnie** [comment]
**copyright issue**
google maps screenshots...

And where's the compass design from ?

**Comment by Sid911** [comment]
@fcartegnie the compass is nothing but screenshot from the pslab application, and the iPhone design I made it myself.. it's very easy... And I am pretty sure we can use Google maps screenshots if we are not using it commercially...

**Comment by Sid911** [comment]
Yeah I was also thinking about miniaturizing the size of pics...

**Comment by Sid911** [comment]
All the things were made in Adobe xd... Instead of just cropping up some photos

**Comment by fcartegnie** [comment]
> @fcartegnie the compass is nothing but screenshot from the pslab application, and the iPhone design I made it myself a long time ago for a different project.. it's very easy... And I am pretty sure we can use Google maps screenshots if we are not using it commercially (even using it to make content which makes money is considered correct)...
> 
> Google isn't coming after us and ask to take us down for using it for a tutorial sweat_smile. Also in this site https://www.google.com/permissions/geoguidelines/ google has allowed us to use google maps for creative purposes .. Plus this comes under free and fair use law of US and similar kind of law in my country.. that is why people don't get DMCA takedowns notices or copyright strike when they show google maps in their videos.
> 

This is not about what can be done by your own interpretation in your own country. 
Commiting content here you *relicense* under Apache terms *worldwide*. Guidelines are not valid for commercial usage, for example.
Not mentioning that if that was possible, you do not even follow the mandatory attribution guidelines.

> Also we are simulating real phone and real map in these screenshots..

We're not doing a screenshot of gmaps running on the phone.

**Comment by Sid911** [comment]
@fcartegnie I think I attributed "screenshot from google maps" ? 😕  in  line 115? I think that should be more clear though

also annotation is allowed so, I guess marking over with labels etc works.

> We're not doing a screenshot of gmaps running on the phone.

I mean the map is supposed to represent a physical map that a person has and the phone mockup is supposed to act as a physical phone that a person might have

**Comment by cweitat** [comment]
@Sid911 the link you sent: 1st paragraph. https://www.google.com/permissions/geoguidelines/
image

essentially, even though this is a open source project, it is bundled with the hardware PSLab for sales

**Comment by Sid911** [comment]
@cweitat right I got it.. I will replace the google map screenshot with something else.. its specifically for pslab, I didn't think this is a software bundled with the hardware... but anyways

**Comment by cweitat** [comment]
Thanks. Do have a look at OpenStreetMaps https://www.openstreetmap.org
The hardware and software relies on one another to be at it's fully functional capability.

**Comment by fcartegnie** [comment]
If you don't see the difference between using a screenshot in a [non]commercial product (with attribution) and bundling/re-licensing someone else I.P., then there's a big concern.

**Comment by Sid911** [comment]
@fcartegnie no.. I thought pslab software and its documentation is not commercial... its a simple open source software like others.. this would work (I think) in something like phimp-me project... but this being "bundled" with the commercially sold hardware makes it complicated. (Atleast this is what I understood from cweitat's comment 😅)

**Comment by fcartegnie** [comment]
> @fcartegnie no.. I thought pslab software and its documentation is not commercial... its a simple open source software like others.. this would work (I think) in something like phimp-me project... but this being "bundled" with the commercially sold hardware makes it complicated. (Atleast this is what I understood from cweitat's comment sweat_smile)

**Even non commercial**, that's re-licensing

**Comment by Sid911** [comment]
yes I got it before 😇... no problem in learning things .. thanks

**Comment by cweitat** [comment]
@Sid911 this repo is maintained by FOSSASIA which is hosting the hardware PSLab and the software aspects of PSLab. It's hard to distinguish whether it is non-commercial. Just play safe and use sources such as OSM which is open to commercialising.

Glad that you learn something from it :)

**Comment by Sid911** [comment]
@cweitat yeah.. I am almost 17 I should know these stuff more 😅. I will surely research more about it this night, btw I will make the changes in a 30minutes.. Thanks for the patience to make me understand 😇

**Comment by Sid911** [comment]
@cweitat @fcartegnie Done .. I have now used the map provided by open street map
image

**Comment by Sid911** [comment]
@cweitat please review this now 😇

**Comment by Sid911** [comment]
@cweitat Done 😇 I removed the bottom grey bar, now it looks like a any other android 10 phone

**Comment by Sid911** [comment]
@fcartegnie please review this 😇.. thanks

**Pull request merged**
