### PR TITLE
Changed image path

### PR DESCRIPTION
**Pull request by NishithP2004**
* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- [ ] Bug fix
- [ ] Feature implementation
- [x] Doc updates

* **Related Issue**

#82 

* **What changes have you introduced?**
I have changed all the image paths to the new images folder.

* **Does this PR introduce a breaking change?**

* **Preview / Steps to verify your work**:
https://github.com/NishithP2004/pslab-documentation

### CODE REVIEW

**Comment by NishithP2004** [comment]
@cweitat Reviews

**Comment by cweitat** [comment]
Conflicts

**Comment by cweitat** [comment]
Conflicts

**Comment by NishithP2004** [comment]
Done @cweitat 
Please review

**Comment by NishithP2004** [comment]
@cweitat Please review

**Pull request merged**
