### PR TITLE
Add experiment for accelorometer

### LINKED ISSUE #64: Add documentation for accelorometer
**Describe the issue**
The documentation for accelorometer is missing. 

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by MuhammadWasif**
* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- [ ] Bug fix
- [x] Doc updates
- [ ] Feature implementation

* **Related Issue**

Fix #64 

* **What changes have you introduced?**
Added documentation for accelorometer along with relevant screenshots

### CODE REVIEW

**Comment by mariobehling** [comment]
Please provide a link to a test page.

**Comment by MuhammadWasif** [comment]
@mariobehling Fixed typo errors
https://github.com/MuhammadWasif/pslab-documentation/blob/master/tutorials/accelerometer.md

**Comment by mariobehling** [comment]
Please fix spelling mistakes.

**Comment by MuhammadWasif** [comment]
> Please fix spelling mistakes.

@mariobehling Please check now

**Pull request merged**
